### ISSUE TITLE
solr-qa 실행시 에러가 발생함.

### ISSUE THREAD

**Issue by amondnet** [amondnet/qa-system#1]
1월 15, 2016 5:05:37 오전 org.apache.solr.common.SolrException log
심각: java.lang.NumberFormatException: For input string: "NUMBER_OF_VERB_FRAMES"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at net.didion.jwnl.data.VerbFrame.initialize(VerbFrame.java:22)
    at opennlp.tools.coref.mention.JWNLDictionary.<init>(JWNLDictionary.java:60)
    at com.tamingtext.qa.AnswerTypeContextGenerator.<init>(AnswerTypeContextGenerator.java:58)
    at com.tamingtext.qa.QuestionQParserPlugin.init(QuestionQParserPlugin.java:115)
    at org.apache.solr.core.SolrCore.createInitInstance(SolrCore.java:445)
    at org.apache.solr.core.SolrCore.initPlugins(SolrCore.java:1612)
    at org.apache.solr.core.SolrCore.initPlugins(SolrCore.java:1606)
    at org.apache.solr.core.SolrCore.initPlugins(SolrCore.java:1639)
    at org.apache.solr.core.SolrCore.initQParsers(SolrCore.java:1556)
    at org.apache.solr.core.SolrCore.<init>(SolrCore.java:555)
    at org.apache.solr.core.CoreContainer.create(CoreContainer.java:483)
    at org.apache.solr.core.CoreContainer.load(CoreContainer.java:335)
    at org.apache.solr.core.CoreContainer$Initializer.initialize(CoreContainer.java:165)
    at org.apache.solr.servlet.SolrDispatchFilter.init(SolrDispatchFilter.java:96)
    at org.mortbay.jetty.servlet.FilterHolder.doStart(FilterHolder.java:97)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:713)
    at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
    at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1282)
    at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:518)
    at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:499)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.mortbay.jetty.handler.HandlerCollection.doStart(HandlerCollection.java:152)
    at org.mortbay.jetty.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:156)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.mortbay.jetty.handler.HandlerCollection.doStart(HandlerCollection.java:152)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
    at org.mortbay.jetty.Server.doStart(Server.java:224)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.mortbay.xml.XmlConfiguration.main(XmlConfiguration.java:985)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.mortbay.start.Main.invokeMain(Main.java:194)
    at org.mortbay.start.Main.start(Main.java:534)
    at org.mortbay.start.Main.start(Main.java:441)
    at org.mortbay.start.Main.main(Main.java:119)

**Comment by amondnet** [comment]
http://sourceforge.net/p/opennlp/discussion/9943/thread/8e6057f9/

**Comment by amondnet** [comment]
https://forums.manning.com/posts/list/30351.page
